{% set version="1.0.1" %}
{% set revision="a21f07c32e99c811f9c3bfd8678721c6e1a51333" %}

package:
  name: tatajuba 
  version: {{ version }}

source:
  git_url: https://github.com/quadram-institute-bioscience/tatajuba.git
  git_rev: {{ revision }}
  md5: unused

build:
  number: 0
  skip: true # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - automake
    - pkg-config
    - make
    - check
    - zlib
    - xz
    - bzip2
  host:
    - check
    - zlib
    - xz
    - bzip2
  run:
    - zlib
    - xz
    - bzip2

test:
  commands:
    - tatajuba -h 

about:
  home: https://github.com/quadram-institute-bioscience/tatajuba
  license: 'GPLv3'
  license_file: https://github.com/quadram-institute-bioscience/tatajuba/blob/master/LICENSE
  summary: 'Identification and classification of homopolymeric tracts from reads (EXPERIMENTAL)'

extra:
  identifiers:
    - biotools:tatajuba
  skip-lints:
    - uses_git_url
    - uses_vcs_url
